version: '3.8'

services:
  printer-web:
    build: .
    container_name: printer-web
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - /var/run/cups/cups.sock:/var/run/cups/cups.sock
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - PRINTER=HP_LaserJet_Professional_M1136_MFP
      - CUPS_SERVER=/var/run/cups/cups.sock
